version: '2'

services: 
  bbps:
    build: .
    image: shintech/bb_mysql_seed:latest
    container_name: bb_mysql_seed
    network_mode: bridge
    env_file:
      - ./bb_mysql_seed.env
    external_links:
      - mysql
    ports:
      - 8000:8000
    restart: always