version: '2'

services: 
  bbps:
    build: .
    image: shintech/bb_mysql_seed:latest
    container_name: bb_mysql_seed
    env_file:
      - ./mysql.env
    links: 
      - mysql
    ports:
      - 8000:8000
    restart: always
  mysql:
    image: mysql
    container_name: mysql
    command: mysqld --user=root --verbose
    volumes:
      - ./init.sql:/init.sql
      - ./import.sh:/import.sh
    environment:
      MYSQL_DATABASE: "development"
      MYSQL_USER: "mike"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"